version: '2'

services:     
  
  interFlightService:
    image: 192.168.160.48:5000/es_interflight/interflight
    container_name: esp12_interflight
    ports: 
      - "12026:12026"
    expose:
      - "12026" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.160.18:3306/airtrafficDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql
    networks:
      - esp12     
    depends_on: 
      - zookeeper
      - kafka

  sensorsService:
    image: 192.168.160.48:5000/es_interflight/sensors
    container_name: esp12_sensors
    ports: 
      - "12025:12025"
    expose:
      - "12025" 
    depends_on: 
      - zookeeper
      - kafka
    networks:
      - esp12  


  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    expose:
      - 2181
    ports:
      - 2181:2181
      
  kafka: 
    image: wurstmeister/kafka
    container_name: kafka
    expose:
      - 9092 
    ports:
      - 9092:9092
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_CREATE_TOPICS: "flightInfo:1:1, flightTerminated:1:1, flightInitiated:1:1"
    depends_on: 
      - zookeeper

networks:
  esp12:
    driver: bridge