server:
  port: 12025
spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.160.18:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer