version: '2'

services: 
  #*app:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: interFlight

  zookeeper:
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      kafka-net:
        ipv4_address: 172.0.0.5
    ports:
      - '2181:2181'
    expose: 
      - '2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'wurstmeister/kafka'
    networks:
      kafka-net:
        ipv4_address: 172.0.0.16
    ports:
      - '9092:9092'
    expose:
      - '9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.0.0.16
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "flightInfo:1:1, flightTerminated:1:1, flightInitiated:1:1"
    depends_on:
      - zookeeper

networks:
  kafka-net:
    ipam:
      driver: default
      config: 
        - subnet: 172.0.0.0/24