version: '2'

services: 
  #*app:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: interFlight

  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      kafka-net  
    ports:
      2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN=yes
  kafka: 
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      9092:9092
    environment: 
      KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER=yes
      KAFKA_CREATE_TOPICS: "flightInfo:1:1, flightTerminated:1:1, flightInitiated:1:1"
      
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

networks:
  kafka-net:
    driver: bridge