version: '2'

services: 
  #*app:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: interFlight

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    expose:
      - 2181
    ports:
      - 2181:2181
  kafka: 
    image: wurstmeister/kafka
    container_name: kafka
    expose:
      - 9092 
    ports:
      - 9092:9092
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "flightInfo:1:1, flightTerminated:1:1"
      
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock